"""Generate the key pairs and JWTs test/sql/token.sql uses (plan/23 T2).

Run once, with the stories venv (pyjwt + cryptography):
    stories/.venv/bin/python test/token/make_tokens.py
Writes test/token/fixtures.sql: psql variables for every token, and
set_config() calls for the public keys. Tokens expire in 2100, so the suite
stays valid; the private keys are not kept.
"""
import base64
import hashlib
import hmac
import json
import pathlib

import jwt
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, rsa

HERE = pathlib.Path(__file__).parent
ISS = "https://issuer.test"
AUD = "letter"
FUTURE = 4102444800   # 2100-01-01
PAST = 946684800      # 2000-01-01


def pem(pub):
    return pub.public_bytes(serialization.Encoding.PEM,
                            serialization.PublicFormat.SubjectPublicKeyInfo).decode()


rsa_a = rsa.generate_private_key(public_exponent=65537, key_size=2048)
rsa_b = rsa.generate_private_key(public_exponent=65537, key_size=2048)
rsa_other = rsa.generate_private_key(public_exponent=65537, key_size=2048)
ec_p256 = ec.generate_private_key(ec.SECP256R1())
ec_p384 = ec.generate_private_key(ec.SECP384R1())
ed = ed25519.Ed25519PrivateKey.generate()

base = {"iss": ISS, "aud": AUD, "sub": "alice", "iat": PAST, "exp": FUTURE}


def tok(key, alg, headers=None, **over):
    claims = {**base, **over}
    for k, v in list(claims.items()):
        if v is None:
            del claims[k]
    return jwt.encode(claims, key, algorithm=alg, headers=headers)


tokens = {
    "rs256_ok": tok(rsa_a, "RS256"),
    "rs384_ok": tok(rsa_a, "RS384"),
    "rs512_ok": tok(rsa_a, "RS512"),
    "es256_ok": tok(ec_p256, "ES256"),
    "es384_ok": tok(ec_p384, "ES384"),
    "eddsa_ok": tok(ed, "EdDSA"),
    "rs256_expired": tok(rsa_a, "RS256", exp=PAST + 3600),
    "rs256_nbf_future": tok(rsa_a, "RS256", nbf=FUTURE - 3600),
    "rs256_wrong_iss": tok(rsa_a, "RS256", iss="https://other.test"),
    "rs256_wrong_aud": tok(rsa_a, "RS256", aud="someone-else"),
    "rs256_aud_list": tok(rsa_a, "RS256", aud=["x", AUD, "y"]),
    "rs256_wrong_key": tok(rsa_other, "RS256"),
    "rs256_no_sub": tok(rsa_a, "RS256", sub=None),
    "rs256_numeric_sub": tok(rsa_a, "RS256", sub=42),
    "rs256_no_exp": tok(rsa_a, "RS256", exp=None),
    "rs256_uid_claim": tok(rsa_a, "RS256", uid="user-7"),
    "rs256_kid_a": tok(rsa_a, "RS256", headers={"kid": "a"}),
    "rs256_kid_b": tok(rsa_b, "RS256", headers={"kid": "b"}),
    "rs256_kid_unknown": tok(rsa_a, "RS256", headers={"kid": "zzz"}),
    "none_alg": jwt.encode({**base}, None, algorithm="none"),
}


def b64u(b):
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()


# the classic confusion: HS256 with the public key's PEM as the secret (pyjwt
# refuses to make one, rightly — by hand)
_hdr = b64u(json.dumps({"alg": "HS256", "typ": "JWT"}).encode())
_pl = b64u(json.dumps(base).encode())
tokens["hs256_pubkey"] = ".".join([_hdr, _pl, b64u(hmac.new(pem(rsa_a.public_key()).encode(),
                                                            f"{_hdr}.{_pl}".encode(), hashlib.sha256).digest())])
# a tampered payload: valid token, subject swapped after signing
h, p, s = tokens["rs256_ok"].split(".")
p2 = jwt.utils.base64url_encode(json.dumps({**base, "sub": "mallory"}).encode()).decode()
tokens["rs256_tampered"] = ".".join([h, p2, s])
tokens["garbage"] = "not.a.token"
tokens["two_parts"] = h + "." + p

keys = {
    "rsa_a": pem(rsa_a.public_key()),
    "rsa_b": pem(rsa_b.public_key()),
    "ec_p256": pem(ec_p256.public_key()),
    "ec_p384": pem(ec_p384.public_key()),
    "ed": pem(ed.public_key()),
}

out = ["-- Generated by test/token/make_tokens.py — do not edit.", ""]
for name, t in tokens.items():
    out.append(f"\\set {name} '{t}'")
out.append("")


def q(text):
    """A psql single-quoted \\set value: backslash escapes are interpreted there."""
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


for name, k in keys.items():
    out.append(f"\\set key_{name} {q(k)}")
out.append(f"\\set key_kid {q('kid=a' + chr(10) + keys['rsa_a'] + 'kid=b' + chr(10) + keys['rsa_b'])}")
out.append(f"\\set key_all {q(keys['rsa_a'] + keys['ec_p256'] + keys['ec_p384'] + keys['ed'])}")
(HERE / "fixtures.sql").write_text("\n".join(out) + "\n")
print(f"wrote {len(tokens)} tokens, {len(keys)} keys")
